baseURL = "http://alanbernstein.github.io"
languageCode = "en-us"
title = "Micro-optimist"
theme = "notepadium"
paginate = 50

[params]
slogan = "Overthinking the small things"
imgPrefix = "https://alanbernstein.net/blog-static/img"

[markup.goldmark.renderer]
unsafe= true  # enable raw HTML in markdown

[markup.highlight]
codeFences = true
noClasses = false

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"